# Generated by Django 3.0.2 on 2020-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('notes', models.TextField(max_length=255)),
                ('twitter', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('google', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
    ]
